# Reinlav — The reindeer lichen on the forest floor. Cool, soft grey-white.
[colors.primary]
background = "#dcdcd4"
foreground = "#2a2822"

[colors.cursor]
cursor = "#425400"
text = "#dcdcd4"

[colors.selection]
background = "#c4c2ae"
text = "#2a2822"

[colors.normal]
black = "#2a2822"
red = "#af3044"
green = "#405200"
yellow = "#755607"
blue = "#365261"
magenta = "#723e57"
cyan = "#285a4b"
white = "#b5b3a6"

[colors.bright]
black = "#5d594f"
red = "#8e152f"
green = "#2a3b00"
yellow = "#5a3f00"
blue = "#203b48"
magenta = "#57283f"
cyan = "#114235"
white = "#f1f0ea"
