# Granskog — The spruce forest behind the lichen. Dark, mossy green-grey.
background #262c24
foreground #dcd9ce
cursor #e2be55
cursor_text_color #262c24
selection_background #3f4a37
selection_foreground #dcd9ce
color0 #323a2f
color1 #f7889a
color2 #abb55a
color3 #e2be55
color4 #98b3c1
color5 #d49fb4
color6 #93b9a9
color7 #c9c5b8
color8 #868b7e
color9 #ffa5b6
color10 #c8d078
color11 #ffda75
color12 #b4cedc
color13 #efbbcf
color14 #afd4c5
color15 #eeebe2
